#![allow(dead_code)]

mod are_they_the_same;
mod assembler_interpreter_i;
mod assembler_interpreter_ii;
mod braking_well;
mod counting_duplicates;
mod directions_reduction;
mod ease_the_stockbroker;
mod evaluate_mathematical_expression;
mod give_me_a_diamond;
mod int32_ipv4;
mod irreducible_sum_of_rationals;
mod john_ann_codewars;
mod last_digit_large_num;
mod longest_vowel_chain;
mod magnitude;
mod meeting;
mod reducing_by_steps;
mod remove_first_and_last_character;
mod smallest_unused_id;
mod split_strings;
mod strings_mix;
mod sums_of_parts;
mod two_oldest_ages;
mod url_shortener;
mod vowel_count;
mod weight_for_weight;
mod what_century;
